import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/layout/Header";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en" data-theme="emerald">
        <body className={inter.className}>
          <main className="max-w-4xl mx-auto p-4">
            <Toaster />
            <Header />
            {children}
          </main>
        </body>
      </html>
    </ClerkProvider>
  );
}
